[chain]
address="0x<address of the contract used for storing the index>"
private_key="<private key of the signer account>"
gateway="<gateway used for interacting with the ethereum blockchain>"
account="<address of the signer account>"

[ipfs]
url="https://api.pinata.cloud/pinning/pinFileToIPFS"
key="<api key of the pinata gateway>"
secret="<api secret of the pinata gateway>"